"use client";

/**
 * "Manipulation check" — Error Level Analysis and compression consistency
 * (FR-6.x).
 *
 * FR-6.6 requires the ELA map to be available as a visual artifact next to
 * the number, "so that a human reviewer can visually inspect flagged regions
 * rather than trust the score alone". The download link honours that — and
 * is hidden when the backend didn't provide a map, rather than offering a
 * link that 404s.
 */
import { Search } from "lucide-react";
import { Accordion, SectionColumns } from "@/components/ui/Accordion";
import { Badge, toneForScore } from "@/components/ui/Badge";
import { DegradedNotice } from "@/components/ui/Banner";
import { FieldLabel } from "@/components/ui/Card";
import { KeyValueList } from "@/components/ui/DataLists";
import { DetectionImage } from "@/components/ui/DetectionImage";
import type { ForensicFindings } from "@/types/report";

export function ForensicsSection({
  forensics,
  placeholderClass,
}: {
  forensics: ForensicFindings;
  /**
   * Note this section shows the ELA MAP, not the original image — that is
   * the whole point of FR-6.6. So it takes no `imageUrl`; its source is
   * `forensics.ela_map_url`.
   */
  placeholderClass: string;
}) {
  const degraded = forensics.status !== "ok";
  const tone = toneForScore(forensics.forensic_suspicion_score);
  const label =
    forensics.forensic_suspicion_score >= 61
      ? "High"
      : forensics.forensic_suspicion_score >= 31
        ? "Moderate"
        : "Low";

  return (
    <Accordion
      icon={<Search className="size-5" />}
      title="Manipulation check"
      summary={forensics.summary}
      badge={
        <Badge tone={degraded ? "moderate" : tone}>
          {degraded ? "Skipped" : label}
        </Badge>
      }
    >
      {degraded ? (
        <DegradedNotice
          reason={
            forensics.unavailable_reason ??
            "The forensics engine did not complete for this image, so no ELA or compression findings are available."
          }
        />
      ) : (
        <SectionColumns>
          <div>
            <FieldLabel>Error-level analysis</FieldLabel>
            <DetectionImage
              src={forensics.ela_map_url}
              placeholderClass={placeholderClass}
              caption="ELA heat map"
              alt="Error level analysis heat map of the analyzed image"
              className="contrast-[1.3] saturate-[.6]"
            />

            {forensics.ela_map_url ? (
              <p className="mt-2 text-[13px]">
                <a
                  href={forensics.ela_map_url}
                  download
                  className="text-blue hover:underline"
                >
                  Download ELA map →
                </a>
              </p>
            ) : (
              <p className="mt-2 text-[13px] text-ink-3">
                The ELA map image is generated by the backend and isn&apos;t
                available for this report.
              </p>
            )}
          </div>

          <div>
            <FieldLabel>Findings</FieldLabel>
            <KeyValueList
              items={[
                {
                  label: "Suspicion score",
                  value: `${Math.round(forensics.forensic_suspicion_score)} / 100`,
                },
                {
                  label: "Candidate edited region",
                  value: forensics.candidate_regions,
                },
                {
                  label: "Compression generations",
                  value: forensics.compression_generations,
                },
                {
                  // FR-6.4: inconsistencies between engines are stated
                  // explicitly rather than quietly averaged into a score.
                  label: "Cross-check vs metadata",
                  value: forensics.metadata_cross_check,
                },
              ]}
            />
          </div>
        </SectionColumns>
      )}
    </Accordion>
  );
}
